### ISSUE TITLE
pug

### ISSUE THREAD

**Issue by mglknFSD** [Van4e3WT/Mutilslider_V43#15]
Наверное тут можно применить цикл

![for](https://user-images.githubusercontent.com/75975369/133816050-b324c8e1-3bfa-4bbe-85b0-e34e908465bb.jpg)

**Comment by Van4e3WT** [comment]
Цикл можно сделать, но получатся громоздкие параметры, т.к. уникальные параметры на каждой строке, с точки зрения форматирования, так, пожалуй, конечно проще поддерживать код

**Comment by Van4e3WT** [comment]
По итогу получается вот такой массив пропсов для цикла и сам цикл: 
![image](https://user-images.githubusercontent.com/57857742/134634144-513eb421-24d7-4b15-bf89-7e6c492d3c44.png)
![image](https://user-images.githubusercontent.com/57857742/134634173-16583402-1438-4794-a75a-7c094d8fafa4.png)
Как оставлять? как было или циклом

**Comment by mglknFSD** [comment]
Я тут, наверное, погорячился. Для параметров цикл не обязателен. Но можно и оставить.
