### ISSUE TITLE
TS

### ISSUE THREAD

**Issue by mglknFSD** [Van4e3WT/Mutilslider_V43#19]
Все константы храним в корне файла и используем специальное именование.

![const](https://user-images.githubusercontent.com/75975369/134768531-72559f33-fa3e-49c6-ba75-a1d701abc539.jpg)

**Comment by mglknFSD** [comment]
- вложенные if
- составные предикаты

![if](https://user-images.githubusercontent.com/75975369/134768603-3c4b3fd2-705b-4cc2-9ae9-e3845d46ecbc.jpg)

**Comment by mglknFSD** [comment]
Для таких вещей опастно полагаться на строки (при наборе строки легко ошибится). Для этих целей есть enum.

![enum](https://user-images.githubusercontent.com/75975369/134768873-ada5e928-3136-46d0-8f31-3da5bf1dc6ad.jpg)

**Comment by mglknFSD** [comment]
Явно public указывать не надо.

![public](https://user-images.githubusercontent.com/75975369/134769002-1c6ddf83-23a6-4332-94f1-207abc5c2345.jpg)

**Comment by mglknFSD** [comment]
Неиспользуемые переменные именуем через underscore.

![not used var](https://user-images.githubusercontent.com/75975369/134769191-a5ad84f3-6faa-4c32-9cbd-5668aa87ee90.jpg)

**Comment by mglknFSD** [comment]
Предпочтительно использовать .forEach, но тут происходит что-то совсем странное.

![forEach](https://user-images.githubusercontent.com/75975369/134769330-bf919b37-a059-4235-9f0d-68ad35e2bda8.jpg)

**Comment by mglknFSD** [comment]
Не семантичное именование.

![semantic](https://user-images.githubusercontent.com/75975369/134769389-cc1ed8a1-8085-47ce-9ffe-d0b3734615f6.jpg)

**Comment by Van4e3WT** [comment]
> Явно public указывать не надо.
> 
> ![public](https://user-images.githubusercontent.com/75975369/134769002-1c6ddf83-23a6-4332-94f1-207abc5c2345.jpg)

Ненадо или необязательно? Просто мне проще с явным определением спецификаторов доступа

**Comment by mglknFSD** [comment]
> Ненадо или необязательно? Просто мне проще с явным определением спецификаторов доступа

public это модификатор по умолчанию, и указывать его явно смысла нет. Но в best practice про это ничего не отмечено, и большой ошибки тут нет. Мое мнение - в проекте не должно быть ничего лишнего, поэтому я бы убрал. На ваше усмотрение.

**Comment by Van4e3WT** [comment]
> Предпочтительно использовать .forEach, но тут происходит что-то совсем странное.
> 
> ![forEach](https://user-images.githubusercontent.com/75975369/134769330-bf919b37-a059-4235-9f0d-68ad35e2bda8.jpg)

Метод в качестве входного параметра принимает число, определяющее количество делений шкалы, которые надо сгенерировать. С помощью цикла `for` генерируем деления шкалы. Как здесь использовать `forEach` не представляю. Почему подчеркнут префиксный предикат? В best practice в примерах предикат также используется (хоть там он постфиксный, не знаю влияет ли это на логику цикла for, но в СИ-образных языках префиксный предикат работал немного быстрее постфиксного, поэтому использовал его, да и в js он возвращает уже измененное значение)

**Comment by Van4e3WT** [comment]
> Не семантичное именование.
> 
> ![semantic](https://user-images.githubusercontent.com/75975369/134769389-cc1ed8a1-8085-47ce-9ffe-d0b3734615f6.jpg)

По поводу переменной `n` исправил, а насчёт `i` в цикле `for` не вижу проблем. С отсылкой на [комментарий](https://github.com/Van4e3WT/TOXIN/issues/35#issuecomment-950292112)

**Comment by mglknFSD** [comment]
> Метод в качестве входного параметра принимает число, определяющее количество делений шкалы, которые надо сгенерировать. С помощью цикла `for` генерируем деления шкалы. Как здесь использовать `forEach` не представляю. Почему подчеркнут префиксный предикат? В best practice в примерах предикат также используется (хоть там он постфиксный, не знаю влияет ли это на логику цикла for, но в СИ-образных языках префиксный предикат работал немного быстрее постфиксного, поэтому использовал его, да и в js он возвращает уже измененное значение)

1 - код пишется по большей части для людей (что бы его было удобно читать и поддерживать), и во-первых такие микрооптимизации не имеют смысла, во-вторых запутывают код. В любом императивном языке ожидается что цикл for выглядит так. `for (let i = 0; i < some; i++) {}`. ++i вносит вопросы зачем это сделано.

2 - по-поводу i в цикле for - тут моя ошибка, это довольно идеоматичное название

3 - forEach для этих целей использовать элементарно.  Можно, например, создать массив и пройтись по нему `new Array(10).fill(null).forEach((_, index) => console.log(index))`. Можно используя этот код создать helper:

```js
function generator(n) {
  return new Array(n).fill(null).map((_, index) => index);
}
```

Можно пойти еще дальше и использовать генераторы. Или импортировать соответсвующие функции из lodash.
Вариантов масса.

**Comment by Van4e3WT** [comment]
@mglknFSD поправил (забыл в коммитах сослаться на ишью), а можно узнать, почему предпочтительнее использовать именно `forEach` вместо `for`? Исключительно из-за читаемости? Или из-за того, что это метод переменной он как-то иначе обрабатывается?

**Comment by mglknFSD** [comment]
> @mglknFSD поправил (забыл в коммитах сослаться на ишью), а можно узнать, почему предпочтительнее использовать именно `forEach` вместо `for`? Исключительно из-за читаемости? Или из-за того, что это метод переменной он как-то иначе обрабатывается?

У нас по бест практис предпочтительное использование forEach. Кроме как читаемости тут нет бенефитов. Если все будут использовать ограниченное число лексем, код коллеги будет более предсказуемым и читать его будет легче
