### ISSUE TITLE
View - Controller

### ISSUE THREAD

**Issue by Geksanit** [Van4e3WT/Mutilslider_V43#21]
Роль контроллера - быть посредником между вью и моделью, позволяя им не зависеть друг от друга.
Модель ни о ком ничего не знает, получает входное значени и отвечает.
И Вью тоже ничего не должен знать, только отображая нужное состояние и сообщая что что-то произошло.
Для проверки паттерна MVC достаточно провести мысленный эксперимент - можно ли заменить модель или вью на другую реализацию но с тем-же интерфейсом?
К модели претензий нет, она соединена через паттерн наблюдатель.
Тогда и Вью надо так же подключить.
![image](https://user-images.githubusercontent.com/31949379/147499299-e7ccdc30-c897-496b-8bb0-b0f61d314a64.png)
на скрине видно, что Вью знает про интерфейс модели, знает как интерпретировать события, как и когда оповещать модель НАПРЯМУЮ, а ведь это должен делать контроллер, реагируюя на эвенты из Вью.

**Comment by Geksanit** [comment]
![image](https://user-images.githubusercontent.com/31949379/147499926-409851b8-8a0d-42f2-abfc-f4c6ea8aa55d.png)
вместе с values можно передать min и max, чтобы один раз передать значение во вью и не дергать  в ней getMin getMax getValue

**Comment by Van4e3WT** [comment]
Обновил компоненты контроллера и вью. Теперь взаимодействие осуществляется с помощью шаблона наблюдателя. Таким же образом теперь взаимодействуют и вью со своими сабвью.

**Comment by Geksanit** [comment]
В целом все правильно. Но getMin и getMax теперь только в тестах использутся(

**Comment by Van4e3WT** [comment]
И правда. Нужно поправить или оставить? Если поправить, то тут вижу два возможных варианта:
1) удалить неиспользуемый функционал (попроще)
